from enum import Enum  
  
class Language(Enum):  
    CHINESE = 'Chinese'  
    GERMAN = 'German'  
    JAPANESE = 'Japanese'
    SPANISH = 'Spanish'  
    FRENCH = 'French'  
    ITALIAN = 'Italian'  
    PORTUGUESE = 'Portuguese'  
    RUSSIAN = 'Russian'  
    KOREAN = 'Korean'  
    ARABIC = 'Arabic'  
    HINDI = 'Hindi'  
    DUTCH = 'Dutch'  
    SWEDISH = 'Swedish'  
    POLISH = 'Polish'  
    HUNGARIAN = 'Hungarian'  
    CZECH = 'Czech'  
    GREEK = 'Greek'  
    NORWEGIAN = 'Norwegian'  
    DANISH = 'Danish'  
    FINNISH = 'Finnish'  
    TURKISH = 'Turkish'